[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "classmanage-app"

[services.volumes]
# 持久化數據庫文件
- type = "volume"
  source = "classmanage-data"
  target = "/app/data"

[environment]
NODE_ENV = "production"
PORT = "${{ PORT }}"
DB_PATH = "/app/data/classroom.db"
AUTO_BACKUP_ENABLED = "true"
BACKUP_INTERVAL_HOURS = "24"
MAX_LOCAL_BACKUPS = "7"

# 備份配置 (需要手動設置)
# BACKUP_WEBHOOK_URL = "your-backup-webhook-url"
# BACKUP_API_KEY = "your-api-key"


